### PR TITLE
ENS relay

### PR DESCRIPTION
**Pull request by ZzzzHui**

### CODE REVIEW

**Comment by guidanoli** [comment]
This needs a rebase.

**Comment by gligneul** [comment]
@ZzzzHui @guidanoli This should go to rollups-contracts repo

**Comment by guidanoli** [comment]
@gligneul Oops, you're right!

**Comment by guidanoli** [comment]
Actually, we thought of an alternative solution: we'll let name resolution occur strictly on the execution layer, and not do caching on the base layer. Because of this, I think we can drop this branch altogether.

What do you think, @ZzzzHui?

**Comment by ZzzzHui** [comment]
Yeah. That was the reason that I didn't move this branch to the new repo, because we didn't agree on this solution

**Pull request closed without merging**
