### PR TITLE
fix(graphql-server): integer coercion in variables

### PR DESCRIPTION
**Pull request by gligneul**
Without this patch, the integer variables are always interpreted as BigInts.

Fixes https://github.com/cartesi/rollups-node/issues/81

### CODE REVIEW

**Review by marcelstanley — APPROVED** [review]

**Comment by tuler** [comment]
Is it necessary to check the value to decide how to parse?

**Comment by gligneul** [comment]
> Is it necessary to check the value to decide how to parse?

The other options are:
- Always converting to int32 integers since we don't have int64 variables.
- Don't convert and change the variables to int64. I don't like this option because it will change the schema.

**Comment by tuler** [comment]
Don't you know the type of the variable from its definition?

**Comment by gligneul** [comment]
@tuler when deserializing the library doesn't know the type of the value it expects. It reads all integer values as int64, that is why it needs to change the type given the value. More info: https://docs.rs/juniper/latest/juniper/trait.ScalarValue.html

**Pull request merged**
