### PR TITLE
Solidity-util v6 and deploy

### PR DESCRIPTION
**Pull request by tuler**
- bump solidity-util to v6
- deploy with deterministic deployment of Safe Singleton Factory
- network configuration using @wagmi/chains
- new deployments
- bump npm dependencies
- bump openzeppelin

### CODE REVIEW

**Comment by pedroargento** [comment]
Will the contracts be verified on testnets?

**Comment by tuler** [comment]
> Will the contracts be verified on testnets?

All contracts are verified on testnets.

**Review by gligneul — APPROVED** [review]

**Review by pedroargento — APPROVED** [review]

**Review by guidanoli — CHANGES_REQUESTED** [review]
I think you forgot to run `prettier` in the `rollups-cli` directory.

**Review by guidanoli — APPROVED** [review]

**Comment by tuler** [comment]
All contracts deployed and verified on all 6 networks.

**Review by gligneul — APPROVED** [review]

**Pull request merged**
