### PR TITLE
Add additional parameters to "create" command

### PR DESCRIPTION
**Pull request by juztamau5**
## Description

This PR adds three additional parameters to the `create` CLI command:

* --jsonFile
* --gasPrice
* --gasLimit

#### --jsonFile

The first parameter, `--jsonFile`, creates a json file that can be imported into a Typescript dapp. The existing option, `--outputFile`, creates a txt file with the address, which can't be imported into Typescript. An alternative to this second (optional) option would be to change everything to use a JSON file with contents like `{"address":"0xF119CC4Ed90379e5E0CC2e5Dd1c8F8750BAfC812"}`.

#### --gasPrice, --gasLimit

The next two commands are useful for test networks that don't have a gas gauge that the web3 provider can automatically use.

#### How has this been tested?

Used in https://github.com/cartesi/rollups-deployment/pull/11 and also tested on Goerli.

### CODE REVIEW

**Comment by tuler** [comment]
Thank you for the PR.

We implemented json file for the deployed dapp in the latest version released today.
We replaced the text file with a json file.

Can you redo your PR, with only the change for the gas price?

**Comment by juztamau5** [comment]
@tuler Done

**Comment by tuler** [comment]
Hey @juztamau5 thanks again for the PR.
We integrated such change to our internal codebase, and should be part of an upcoming release, expected for end of January.
I'll just close the PR.

**Comment by juztamau5** [comment]
cool thanks!

**Pull request closed without merging**
